### ISSUE TITLE
Arrow function should build into es5 before publish

### ISSUE THREAD

**Issue by ycjcl868** [sindresorhus/split-on-first#3]
https://github.com/sindresorhus/split-on-first/blob/master/index.js#L3

**Comment by sindresorhus** [comment]
This module mainly targets Node.js, not the browser. It's up to you to transpile it with Babel if you want to use it in the browser. You can find a more detailed explanation here: https://github.com/sindresorhus/ama/issues/446

If you use Webpack, check out [`babel-engine-plugin`](https://github.com/SamVerschueren/babel-engine-plugin), which transpiles only the dependencies that needs to be transpiled.

If you use Create React App, upgrade to [Create React App v2](https://reactjs.org/blog/2018/10/01/create-react-app-v2.html). It supports automatic transpilation of dependencies, which will make this package *just work*.

**Comment by ycjcl868** [comment]
https://github.com/umijs/es5-imcompatible-versions/pull/26

**Comment by woshiguabi** [comment]
https://github.com/sindresorhus/query-string/commit/73e57caabfdea7d17966fdf2621a178c472a15a1

@ycjcl868 Maybe you are using query-string > 6. This package only supports Node.js since v6.
