### ISSUE TITLE
IE 11 throws error due to use of reserved keyword (string) as function parameter

### ISSUE THREAD

**Issue by oneillsp96** [sindresorhus/split-on-first#6]
My app recently stopped working in IE 11, I tracked this down to a piece of your code that we are pulling in due to our use of the query-string module which uses split-on-first.

The issue is you're using a reserved keyword (string) as a function param here:

module.exports = (string, separator) => {
	if (!(typeof string === 'string' && typeof separator === 'string')) {
		throw new TypeError('Expected the arguments to be of type `string`');
	}

While most modern browsers seem to be able to understand what the code really meant, not IE 11.
A simple fix would be changing string to str in this particular function

**Comment by sindresorhus** [comment]
Sorry, I'm not supporting IE11 here. There are many other things with `query-string` that will not work with IE11 too. You're better off transpiling everything.

**Comment by JackHowa** [comment]
Had the same issue as @oneillsp96
