### ISSUE TITLE
Non spec compliance

### ISSUE THREAD

**Issue by Richienb** [sindresorhus/split-on-first#7]
Using `'abc'.split('')`, this value is given:

```js
["a", "b", "c"]
```

But when using `splitOnFirst('abc', '')`, this expected result was not given:

```js
["a", "bc"]
```

Instead, the value was:

```js
["abc"]
```

**Comment by sindresorhus** [comment]
I don't like the magic behavior of `''` for the built-in `.split()` and it doesn't really make sense here as it's meant to split a string into an array, but I also don't know why I went with `['abc']`. I think it should just return an empty array in this case, and the behavior clearly documented.

**Comment by Richienb** [comment]
@sindresorhus I've just opened #8.

**Comment by sindresorhus** [comment]
Now I remember why I went with the current behavior:

```
❯ node
> 'foo'.split('abc')
[ 'foo' ]
```
